// Search action types
export const SEARCH_BAR_VALUE_CHANGED = 'SEARCH_BAR_VALUE_CHANGED';

// Stock peers action types
export const STOCK_PEERS_LOAD = 'STOCK_PEERS_LOAD';
export const STOCK_PEERS_LOADING = 'STOCK_PEERS_LOADING';
export const STOCK_PEERS_LOAD_SUCCESS = 'STOCK_PEERS_LOAD_SUCCESS';
export const STOCK_PEERS_LOAD_FAILED = 'STOCK_PEERS_LOAD_FAILED';

// Stock price action types
export const STOCK_PRICE_DATA_LOAD = 'STOCK_PRICE_DATA_LOAD';
export const STOCK_PRICE_DATA_LOADING = 'STOCK_PRICE_DATA_LOADING';
export const STOCK_PRICE_DATA_LOAD_SUCCESS = 'STOCK_PRICE_DATA_LOAD_SUCCESS';
export const STOCK_PRICE_DATA_LOAD_FAILED = 'STOCK_PRICE_DATA_LOAD_FAILED';